apiVersion: v1
kind: Service
metadata:
  name: zuri-frontend-service
  namespace: zuri-market
  labels:
    app: zuri-frontend
    app.kubernetes.io/name: zuri-market
    app.kubernetes.io/component: frontend
    demo.zuri-market/runtime-cluster: runtime-k3s-cluster
spec:
  selector:
    app: zuri-frontend
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
  type: NodePort
